version: '3.8'

services:
  ml-optimizer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ml-optimizer
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - CUDA_VISIBLE_DEVICES=0
    volumes:
      - ./workspace:/workspace
      - ./models:/workspace/models
      - ./data:/workspace/data
      - ./results:/workspace/results
    ports:
      - "8888:8888"  # Jupyter
      - "6006:6006"  # TensorBoard
    shm_size: 16g
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    command: >
      bash -c "
        nvidia-smi &&
        python /workspace/scripts/system_info.py &&
        jupyter notebook --allow-root --no-browser --ip=0.0.0.0 --port=8888
      "
